### PR TITLE
Added DisplayFormat option

### PR DESCRIPTION
**Pull request by MFava91**
Hi @nikhil-001mehta . First of all, thanks for your amazing works. I've started to use your date range picker in a new project at work, we've easily customized it, and it looks amazing. 
I have a problem with the dates format, in fact, I need to use a format like **'DD MMM'**. 
At the beginning, I've changed the `format` options but I have a lot of problems with the management of the dates.
So I added the new option `DisplayFormat`: it is used to customize the format of the dates displayed.

Please take a look and let me know what you think.

### CODE REVIEW

**Comment by nikhil-001mehta** [comment]
Thanks a lot @MFava91 I am glad that my code is contributing to minimize your efforts and I would like to do so in future too. 
I did not get one thing though, You could have simply used 'format' option. I did not get What exactly you are trying to accomplish here? May be I can get better insights if you can please elaborate what problems you are facing with current code in place. And may be we can come up with more effective solution in this discussion.
Correct me if I am wrong.

**Comment by MFava91** [comment]
I give you a [plunker](https://plnkr.co/edit/r8hXbabEx1A2QyeXvzwP?p=preview) with an example.

In the first case, I have only set the format to **'DD MMM'**. The other options are in another format and as we expect, all are broken.
In the second case, I set the format to **'DD MMM'** and also the other options (startDate, endDate, minDate and maxDate). All seems work well, but this has a limitation. In fact, I can't select a date before and after this year (ex: _29/01/2019_). This is caused because the year is missing on the format.  I don't want this limitation so I added the new option.

I know this is a simplistic solution, but for a better management of your code, I think that you should be changed a lot of the business logic.

**Comment by nikhil-001mehta** [comment]
Thanks a ton @MFava91 
I did took a look at the plunker you have provided. And in first case it will break since the daterangepicker expects all dates in options in align with the format provided in options. 
Regarding your solution, just to clarify things, I am guessing you are keeping format as 'DD/MM/YYYY' and using displayformat as 'DD MMM'. With this situation I am happy with your solution.

**Comment by MFava91** [comment]
> Regarding your solution, just to clarify things, I am guessing you are keeping format as 'DD/MM/YYYY' and using displayformat as 'DD MMM'.

Yes, it's exactly what I'm doing and all seem work like a charm ;)

**Pull request merged**
